# Generated by Django 6.0 on 2025-12-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_mgr', '0003_alter_book_author_alter_book_isbn_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_mgr.bookstorage'),
        ),
    ]
