# Generated by Django 6.0 on 2025-12-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_mgr', '0004_alter_book_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstorage',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
